version: "3.9"
services:
  web:
    build: .
    environment:
      - PORT=3000
      - INSTAGRAM_USERNAME=anujpflash
      - INSTAGRAM_PASSWORD=ThisIsMyPassword
    ports:
      - "${PORT}:${PORT}"
    